excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - variable_name_max_length
